### ISSUE TITLE
Gracefully handle dependency errors

### ISSUE THREAD

**Issue by ajreading** [castlegateit/cgit-wp-postcard#2]
If Postcard is activated before Postman it will throw a fatal error, but only after activating the plugin. This results in a fatal error whereby you cannot then access the plugins page to enable or disable any other plugins.

`Fatal error: Class 'Cgit\Postman' not found in /xxx/wp-content/plugins/cgit-wp-postcard/src/Cgit/Postcard.php on line 103`

Can we add some sensible checks for other plugin dependencies to prevent this from happening?

**Comment by johnkhughes** [comment]
I've added a dependency check to v2.4, which won't let you activate the plugin if Postman is missing.
